const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toISOString().slice(0,10);
const nowTime=()=>new Date().toTimeString().slice(0,5);
const uid=(p)=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,5);
const sampleUsers=[
 {user_id:'U0001',name:'山田 太郎',kana:'ヤマダ タロウ',sex:'男',birth_date:'1978-05-12',unit:'Aユニット',diagnoses:'脳性麻痺',bowel_notes:'硬便傾向',normal_interval:2,caution_days:2,warning_days:4,status:'入所中'},
 {user_id:'U0002',name:'佐藤 花子',kana:'サトウ ハナコ',sex:'女',birth_date:'1988-09-01',unit:'Aユニット',diagnoses:'てんかん',bowel_notes:'腹部膨満に注意',normal_interval:1,caution_days:2,warning_days:3,status:'入所中'},
 {user_id:'U0003',name:'鈴木 一郎',kana:'スズキ イチロウ',sex:'男',birth_date:'1969-11-20',unit:'Bユニット',diagnoses:'知的障害',bowel_notes:'下剤頓用あり',normal_interval:2,caution_days:3,warning_days:4,status:'入所中'},
 {user_id:'U0004',name:'高橋 美咲',kana:'タカハシ ミサキ',sex:'女',birth_date:'1994-02-18',unit:'Bユニット',diagnoses:'自閉スペクトラム症',bowel_notes:'環境変化で便秘傾向',normal_interval:2,caution_days:2,warning_days:4,status:'入所中'}
];
const d=(offset)=>{const x=new Date();x.setDate(x.getDate()+offset);return x.toISOString().slice(0,10)};
const sampleRecords=[
 {record_id:'R001',user_id:'U0001',date:d(-3),time:'08:10',bowel:'あり',amount:'中',bristol:'2',color:'茶',abdominal_pain:'なし',bloating:'なし',symptoms:'',care:'',memo:'硬め',staff_id:'S01',created_at:'',updated_at:''},
 {record_id:'R002',user_id:'U0002',date:d(-1),time:'07:40',bowel:'あり',amount:'少',bristol:'3',color:'茶',abdominal_pain:'なし',bloating:'あり',symptoms:'',care:'',memo:'',staff_id:'S02',created_at:'',updated_at:''},
 {record_id:'R003',user_id:'U0003',date:d(-4),time:'09:20',bowel:'あり',amount:'多',bristol:'4',color:'茶',abdominal_pain:'なし',bloating:'なし',symptoms:'',care:'',memo:'',staff_id:'S01',created_at:'',updated_at:''},
 {record_id:'R004',user_id:'U0004',date:d(0),time:'06:55',bowel:'あり',amount:'中',bristol:'4',color:'茶',abdominal_pain:'なし',bloating:'なし',symptoms:'',care:'',memo:'朝食前',staff_id:'S03',created_at:'',updated_at:''}
];
const sampleLax=[{laxative_id:'L001',user_id:'U0003',date:d(-1),time:'20:00',type:'頓用',name:'下剤A',dose:'1錠',reason:'排便3日なし',staff_id:'S02',memo:''}];
let users=JSON.parse(localStorage.getItem('ps_users')||'null')||sampleUsers;
let records=JSON.parse(localStorage.getItem('ps_records')||'null')||sampleRecords;
let laxatives=JSON.parse(localStorage.getItem('ps_lax')||'null')||sampleLax;
let settings=JSON.parse(localStorage.getItem('ps_settings')||'null')||{yellow:2,orange:3,red:4,laxHours:24};
const save=()=>{localStorage.setItem('ps_users',JSON.stringify(users));localStorage.setItem('ps_records',JSON.stringify(records));localStorage.setItem('ps_lax',JSON.stringify(laxatives));localStorage.setItem('ps_settings',JSON.stringify(settings));};
function daysSince(date){if(!date)return 999;const a=new Date(date+'T00:00:00'),b=new Date(today()+'T00:00:00');return Math.max(0,Math.floor((b-a)/86400000));}
function lastBowel(u){return records.filter(r=>r.user_id===u&&r.bowel==='あり').sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0]||null}
function lastLax(u){return laxatives.filter(r=>r.user_id===u).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0]||null}
function hoursSince(dt,tm){if(!dt)return null;return Math.max(0,Math.floor((Date.now()-new Date(dt+'T'+(tm||'00:00')).getTime())/3600000))}
function statusFor(u){const user=users.find(x=>x.user_id===u),lb=lastBowel(u),days=lb?daysSince(lb.date):999;const y=user?.caution_days||settings.yellow, r=user?.warning_days||settings.red, o=Math.min(r-1,Math.max(y+1,settings.orange));let s='green';if(days>=r)s='red';else if(days>=o)s='orange';else if(days>=y)s='yellow';const lx=lastLax(u);if(lx&&hoursSince(lx.date,lx.time)>=settings.laxHours&&(!lb || (lb.date+lb.time)<(lx.date+lx.time)))s=s==='red'?'red':'orange';return {s,days,lb,lx,laxHours:lx?hoursSince(lx.date,lx.time):null};}
const cls=s=>'status-'+s; const label={green:'通常',yellow:'確認',orange:'注意',red:'要確認'};
function render(){renderSummary();renderAlerts();renderRecent();renderUsers();renderAnalysis();populateSelects();}
function renderSummary(){const arr=users.map(u=>statusFor(u.user_id));const todayIds=new Set(records.filter(r=>r.date===today()&&r.bowel==='あり').map(r=>r.user_id));$('#summaryGrid').innerHTML=`<div class="summary-card pink"><small>利用者</small><strong>${users.length}</strong><span>登録中</span></div><div class="summary-card blue"><small>本日排便あり</small><strong>${todayIds.size}</strong><span>人</span></div><div class="summary-card yellow"><small>確認・注意</small><strong>${arr.filter(x=>x.s==='yellow'||x.s==='orange').length}</strong><span>人</span></div><div class="summary-card red"><small>要確認</small><strong>${arr.filter(x=>x.s==='red').length}</strong><span>人</span></div>`}
function renderAlerts(){const list=users.map(u=>({u,...statusFor(u.user_id)})).filter(x=>x.s!=='green').sort((a,b)=>['red','orange','yellow'].indexOf(a.s)-['red','orange','yellow'].indexOf(b.s));$('#alertList').innerHTML=list.length?list.map(x=>`<div class="alert-item ${cls(x.s)}"><span class="status-dot"></span><div><strong>${x.u.name}</strong><span>排便なし ${x.days===999?'記録なし':x.days+'日'}${x.lx&&(!x.lb||(x.lb.date+x.lb.time)<(x.lx.date+x.lx.time))?` ／ 下剤後 ${x.laxHours}時間・排便記録なし`:''}</span></div><span class="badge">${label[x.s]}</span></div>`).join(''):'<div class="empty">現在、要確認の利用者はいません。</div>'}
function renderRecent(){const rs=[...records].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).slice(0,8);$('#recentBody').innerHTML=rs.map(r=>{const u=users.find(x=>x.user_id===r.user_id);const lx=laxatives.find(l=>l.user_id===r.user_id&&l.date===r.date);return `<tr><td>${u?.name||r.user_id}</td><td>${r.date} ${r.time}</td><td>${r.bowel}</td><td>${r.amount||'－'}</td><td>${r.bristol||'－'}</td><td>${lx?lx.name:'－'}</td><td>${r.memo||'－'}</td></tr>`}).join('')}
function renderUsers(){const q=($('#userSearch')?.value||'').toLowerCase(),f=$('#statusFilter')?.value||'all';const list=users.filter(u=>`${u.user_id}${u.name}${u.kana}${u.unit}`.toLowerCase().includes(q)).filter(u=>f==='all'||statusFor(u.user_id).s===f);$('#userCards').innerHTML=list.map(u=>{const x=statusFor(u.user_id);return `<div class="user-card ${cls(x.s)}"><div class="name-row"><div><h3>${u.name}</h3><span class="meta">${u.user_id} ｜ ${u.unit||'所属なし'}</span></div><span class="badge">${label[x.s]}</span></div><div class="big">${x.days===999?'－':x.days+'日'} <small style="font-size:12px;color:var(--muted)">排便なし</small></div><div class="meta">最終排便：${x.lb?x.lb.date+' '+x.lb.time:'記録なし'}</div><div class="mini-row"><span class="mini-pill">${u.diagnoses||'病名未登録'}</span>${x.lx?`<span class="mini-pill">下剤後 ${x.laxHours}h</span>`:''}</div><p class="meta">${u.bowel_notes||'注意事項なし'}</p></div>`}).join('')||'<div class="empty">該当する利用者はいません。</div>'}
function renderAnalysis(){const bowelYes=records.filter(r=>r.bowel==='あり');const avg=users.length?(bowelYes.length/users.length).toFixed(1):0;$('#facilityStats').innerHTML=`<div class="stat"><span>排便記録</span><b>${bowelYes.length}</b><small>件</small></div><div class="stat"><span>下剤記録</span><b>${laxatives.length}</b><small>件</small></div><div class="stat"><span>利用者あたり</span><b>${avg}</b><small>件</small></div><div class="stat"><span>要確認</span><b>${users.filter(u=>statusFor(u.user_id).s==='red').length}</b><small>人</small></div>`;renderPersonalInsight();const hard=bowelYes.filter(r=>['1','2'].includes(r.bristol)).length,soft=bowelYes.filter(r=>['6','7'].includes(r.bristol)).length;$('#trendCards').innerHTML=`<div class="trend-card"><b>硬便傾向</b><p>Bristol 1〜2：${hard}件</p></div><div class="trend-card"><b>軟便傾向</b><p>Bristol 6〜7：${soft}件</p></div><div class="trend-card"><b>下剤後フォロー</b><p>現在 ${users.filter(u=>{const x=statusFor(u.user_id);return x.lx&&(!x.lb||(x.lb.date+x.lb.time)<(x.lx.date+x.lx.time))}).length}人</p></div>`}
function renderPersonalInsight(){const id=$('#analysisUser')?.value||users[0]?.user_id;if(!id)return;const u=users.find(x=>x.user_id===id),rs=records.filter(r=>r.user_id===id&&r.bowel==='あり').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const intervals=[];for(let i=1;i<rs.length;i++)intervals.push((new Date(rs[i].date)-new Date(rs[i-1].date))/86400000);const avgi=intervals.length?(intervals.reduce((a,b)=>a+b,0)/intervals.length).toFixed(1):'データ不足';const hard=rs.filter(r=>['1','2'].includes(r.bristol)).length;const lx=laxatives.filter(l=>l.user_id===id).length;$('#personalInsights').innerHTML=`<b>${u?.name||id}</b><br>平均排便間隔：${avgi}${avgi==='データ不足'?'':'日'}<br>硬便（Bristol 1〜2）：${hard}件<br>下剤記録：${lx}件<br><br><strong>この人、こんな感じかも</strong><br>${hard>=2?'硬めの便が続く傾向があります。':'現時点では強い硬便傾向は目立ちません。'} ${lx>=2?'下剤使用との関係も継続して確認できます。':''}`}
function populateSelects(){const opts=users.map(u=>`<option value="${u.user_id}">${u.name}（${u.user_id}）</option>`).join('');const cur=$('#analysisUser')?.value;$('#recordUser').innerHTML=opts;$('#analysisUser').innerHTML=opts;if(cur&&users.some(u=>u.user_id===cur))$('#analysisUser').value=cur;}
function showTab(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));if(id==='analysis')renderAnalysis();}
$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));$$('[data-open-record]').forEach(b=>b.addEventListener('click',()=>{$('#recordDate').value=today();$('#recordTime').value=nowTime();$('#recordDialog').showModal()}));$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#addUserBtn').onclick=()=>$('#userDialog').showModal();$('#userSearch').oninput=renderUsers;$('#statusFilter').onchange=renderUsers;$('#analysisUser').onchange=renderPersonalInsight;
$('#saveRecord').onclick=()=>{const r={record_id:uid('R'),user_id:$('#recordUser').value,date:$('#recordDate').value,time:$('#recordTime').value,bowel:$('#bowel').value,amount:$('#amount').value,bristol:$('#bristol').value,color:'',abdominal_pain:$('#pain').value,bloating:$('#bloating').value,symptoms:'',care:$('#care').value,memo:$('#memo').value,staff_id:'DEMO',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};records.push(r);if($('#laxName').value.trim())laxatives.push({laxative_id:uid('L'),user_id:r.user_id,date:r.date,time:r.time,type:$('#laxType').value,name:$('#laxName').value,dose:$('#laxDose').value,reason:$('#laxReason').value,staff_id:'DEMO',memo:''});save();render();$('#recordDialog').close();$('#recordForm').reset();}
$('#saveUser').onclick=()=>{if(!$('#newUserId').value||!$('#newUserName').value)return alert('利用者IDと氏名を入力してください');users.push({user_id:$('#newUserId').value.trim(),name:$('#newUserName').value.trim(),kana:$('#newUserKana').value.trim(),sex:'',birth_date:'',unit:$('#newUserUnit').value.trim(),diagnoses:$('#newUserDx').value.trim(),bowel_notes:$('#newUserNotes').value.trim(),normal_interval:2,caution_days:settings.yellow,warning_days:settings.red,status:'入所中'});save();render();$('#userDialog').close();}
function csvEscape(v){v=v??'';return /[",\n]/.test(v)?'"'+String(v).replaceAll('"','""')+'"':v}
function downloadCSV(filename,rows,headers){const s='\ufeff'+headers.join(',')+'\n'+rows.map(r=>headers.map(h=>csvEscape(r[h])).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv;charset=utf-8'}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}
$('#exportRecords').onclick=()=>downloadCSV('bowel_records.csv',records,['record_id','user_id','date','time','bowel','amount','bristol','color','abdominal_pain','bloating','symptoms','care','memo','staff_id','created_at','updated_at']);
$('#exportUsers').onclick=()=>downloadCSV('users.csv',users,['user_id','name','kana','sex','birth_date','unit','diagnoses','bowel_notes','normal_interval','caution_days','warning_days','status']);
$('#exportLaxatives').onclick=()=>downloadCSV('laxative_records.csv',laxatives,['laxative_id','user_id','date','time','type','name','dose','reason','staff_id','memo']);
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(x=>x!==''))rows.push(row);const h=rows.shift().map(x=>x.replace(/^\ufeff/,''));return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
$('#csvFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const data=parseCSV(await f.text());let type='';if(data[0]?.user_id&&data[0]?.name)type='users';else if(data[0]?.record_id)type='records';else if(data[0]?.laxative_id)type='lax';if(!type){$('#importResult').textContent='形式を判定できませんでした。';return}const map={users:['user_id',()=>users,v=>users=v],records:['record_id',()=>records,v=>records=v],lax:['laxative_id',()=>laxatives,v=>laxatives=v]};const [key,get,set]=map[type];const base=[...get()];data.forEach(x=>{const i=base.findIndex(y=>y[key]===x[key]);if(i>=0)base[i]={...base[i],...x};else base.push(x)});set(base);save();render();$('#importResult').innerHTML=`<b>${data.length}件</b> を取り込みました（${type}）。`;e.target.value=''};
$('#yellowDays').value=settings.yellow;$('#orangeDays').value=settings.orange;$('#redDays').value=settings.red;$('#laxHours').value=settings.laxHours;$('#saveSettings').onclick=()=>{settings={yellow:+$('#yellowDays').value,orange:+$('#orangeDays').value,red:+$('#redDays').value,laxHours:+$('#laxHours').value};save();render();alert('設定を保存しました')};
render();
